-- ERPmini Fase 1 — versionamento seguro dos snapshots.
-- Migração aditiva: preserva todos os snapshots existentes e mantém
-- compatibilidade com clientes antigos durante a atualização gradual.

begin;

create extension if not exists pgcrypto;

alter table public.erpmini_cloud_data
  add column if not exists version bigint not null default 1,
  add column if not exists data_hash text,
  add column if not exists updated_by_device text;

update public.erpmini_cloud_data
set data_hash = encode(
  digest(convert_to(data::text, 'UTF8'), 'sha256'),
  'hex'
)
where data_hash is null;

create table if not exists public.erpmini_cloud_revisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  version bigint not null,
  data jsonb not null,
  data_hash text not null,
  updated_by_device text,
  created_at timestamptz not null default now(),
  constraint erpmini_cloud_revisions_user_version_key unique (user_id, version)
);

create index if not exists erpmini_cloud_revisions_user_created_idx
  on public.erpmini_cloud_revisions (user_id, created_at desc);

create table if not exists public.erpmini_sync_conflicts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  expected_version bigint not null,
  current_version bigint not null,
  device_id text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create index if not exists erpmini_sync_conflicts_user_created_idx
  on public.erpmini_sync_conflicts (user_id, created_at desc);

alter table public.erpmini_cloud_revisions enable row level security;
alter table public.erpmini_sync_conflicts enable row level security;

drop policy if exists erpmini_cloud_revisions_read on public.erpmini_cloud_revisions;
create policy erpmini_cloud_revisions_read
on public.erpmini_cloud_revisions
for select
to authenticated
using (
  (select auth.uid()) = user_id
  or public.erpmini_is_platform_admin()
);

drop policy if exists erpmini_cloud_revisions_insert on public.erpmini_cloud_revisions;
create policy erpmini_cloud_revisions_insert
on public.erpmini_cloud_revisions
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  or public.erpmini_is_platform_admin()
);

drop policy if exists erpmini_cloud_revisions_delete on public.erpmini_cloud_revisions;
create policy erpmini_cloud_revisions_delete
on public.erpmini_cloud_revisions
for delete
to authenticated
using (
  (select auth.uid()) = user_id
  or public.erpmini_is_platform_admin()
);

drop policy if exists erpmini_sync_conflicts_read on public.erpmini_sync_conflicts;
create policy erpmini_sync_conflicts_read
on public.erpmini_sync_conflicts
for select
to authenticated
using (
  (select auth.uid()) = user_id
  or public.erpmini_is_platform_admin()
);

drop policy if exists erpmini_sync_conflicts_insert on public.erpmini_sync_conflicts;
create policy erpmini_sync_conflicts_insert
on public.erpmini_sync_conflicts
for insert
to authenticated
with check (
  (select auth.uid()) = user_id
  or public.erpmini_is_platform_admin()
);

drop policy if exists erpmini_sync_conflicts_update on public.erpmini_sync_conflicts;
create policy erpmini_sync_conflicts_update
on public.erpmini_sync_conflicts
for update
to authenticated
using (
  (select auth.uid()) = user_id
  or public.erpmini_is_platform_admin()
)
with check (
  (select auth.uid()) = user_id
  or public.erpmini_is_platform_admin()
);

grant select, insert, delete on public.erpmini_cloud_revisions to authenticated;
grant select, insert, update on public.erpmini_sync_conflicts to authenticated;
grant usage, select on sequence public.erpmini_cloud_revisions_id_seq to authenticated;
grant usage, select on sequence public.erpmini_sync_conflicts_id_seq to authenticated;

create or replace function public.erpmini_version_cloud_snapshot()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    new.version := greatest(coalesce(new.version, 1), 1);
    new.data_hash := encode(
      digest(convert_to(new.data::text, 'UTF8'), 'sha256'),
      'hex'
    );
    new.updated_at := now();
    return new;
  end if;

  if new.data is distinct from old.data then
    insert into public.erpmini_cloud_revisions (
      user_id,
      version,
      data,
      data_hash,
      updated_by_device,
      created_at
    )
    values (
      old.user_id,
      old.version,
      old.data,
      coalesce(
        old.data_hash,
        encode(digest(convert_to(old.data::text, 'UTF8'), 'sha256'), 'hex')
      ),
      old.updated_by_device,
      coalesce(old.updated_at, now())
    )
    on conflict (user_id, version) do nothing;

    new.version := old.version + 1;
    new.data_hash := encode(
      digest(convert_to(new.data::text, 'UTF8'), 'sha256'),
      'hex'
    );

    delete from public.erpmini_cloud_revisions
    where id in (
      select id
      from public.erpmini_cloud_revisions
      where user_id = old.user_id
      order by version desc
      offset 30
    );
  else
    new.version := old.version;
    new.data_hash := old.data_hash;
  end if;

  new.user_id := old.user_id;
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.erpmini_version_cloud_snapshot() from public;

drop trigger if exists erpmini_cloud_snapshot_versioning
  on public.erpmini_cloud_data;

create trigger erpmini_cloud_snapshot_versioning
before insert or update on public.erpmini_cloud_data
for each row
execute function public.erpmini_version_cloud_snapshot();

create or replace function public.erpmini_save_cloud_snapshot(
  p_data jsonb,
  p_expected_version bigint,
  p_device_id text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_current public.erpmini_cloud_data%rowtype;
  v_saved public.erpmini_cloud_data%rowtype;
  v_expected bigint := greatest(coalesce(p_expected_version, 0), 0);
  v_device text := nullif(left(trim(coalesce(p_device_id, '')), 120), '');
begin
  if v_user_id is null then
    raise exception 'Authentication required'
      using errcode = '42501';
  end if;

  if p_data is null or jsonb_typeof(p_data) <> 'object' then
    raise exception 'Snapshot must be a JSON object'
      using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));

  select *
  into v_current
  from public.erpmini_cloud_data
  where user_id = v_user_id
  for update;

  if not found then
    if v_expected <> 0 then
      return jsonb_build_object(
        'status', 'conflict',
        'expected_version', v_expected,
        'current_version', 0
      );
    end if;

    insert into public.erpmini_cloud_data (
      user_id,
      data,
      version,
      updated_by_device,
      created_at,
      updated_at
    )
    values (
      v_user_id,
      p_data,
      1,
      v_device,
      now(),
      now()
    )
    returning * into v_saved;

    return jsonb_build_object(
      'status', 'saved',
      'version', v_saved.version,
      'data_hash', v_saved.data_hash,
      'updated_at', v_saved.updated_at
    );
  end if;

  if v_current.version <> v_expected then
    insert into public.erpmini_sync_conflicts (
      user_id,
      expected_version,
      current_version,
      device_id
    )
    values (
      v_user_id,
      v_expected,
      v_current.version,
      v_device
    );

    return jsonb_build_object(
      'status', 'conflict',
      'expected_version', v_expected,
      'current_version', v_current.version,
      'updated_at', v_current.updated_at,
      'updated_by_device', v_current.updated_by_device
    );
  end if;

  update public.erpmini_cloud_data
  set data = p_data,
      updated_by_device = v_device
  where user_id = v_user_id
  returning * into v_saved;

  return jsonb_build_object(
    'status', 'saved',
    'version', v_saved.version,
    'data_hash', v_saved.data_hash,
    'updated_at', v_saved.updated_at
  );
end;
$$;

revoke all on function public.erpmini_save_cloud_snapshot(jsonb, bigint, text)
  from public;
revoke all on function public.erpmini_save_cloud_snapshot(jsonb, bigint, text)
  from anon;
grant execute on function public.erpmini_save_cloud_snapshot(jsonb, bigint, text)
  to authenticated;

commit;
